name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect and what actually happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node, browser, OpenClaw Gateway version
